app:
  scheduler:
    enable: true
    interval: 5000            # Задержка в миллисекундах
    force-check-delay: 10000  # Задержка в миллисекундах

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

api:
  github:
    baseUrl: https://api.github.com/
  stackoverflow:
    baseUrl: https://api.stackexchange.com/2.3/
