app:
  scheduler:
    enable: true
    interval: 10000           # Задержка в миллисекундах
    # TODO : в будущем внедрить force-check-delay
    force-check-delay: 15000  # Задержка в миллисекундах
  database-access-type: jpa  # jdbc / jpa / jooq

spring:
  liquibase:
    enabled: false
  application:
    name: scrapper
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

api:
  bot:
    defaultUrl: http://localhost:8090
  github:
    defaultUrl: https://api.github.com/
  stackoverflow:
    defaultUrl: https://api.stackexchange.com/2.3/

springdoc:
  swagger-ui:
    path: /swagger-ui
