app:
  database-access-type: jpa  # jdbc / jpa / jooq
  scheduler:
    enable: true
    interval: 10000           # Задержка в миллисекундах
    # TODO : в будущем внедрить force-check-delay
    force-check-delay: 15000  # Задержка в миллисекундах

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

api:
  bot:
    defaultUrl: http://localhost:8090
  github:
    defaultUrl: https://api.github.com/
  stackoverflow:
    defaultUrl: https://api.stackexchange.com/2.3/

springdoc:
  swagger-ui:
    path: /swagger-ui
