/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables.records;

import edu.java.scrapper.domain.jooq.tables.Links;
import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinksRecord extends UpdatableRecordImpl<LinksRecord> implements Record5<Long, String, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINKS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINKS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINKS.URL</code>.
     */
    public void setUrl(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINKS.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 2048)
    @NotNull
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>LINKS.LAST_UPDATED</code>.
     */
    public void setLastUpdated(@NotNull LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINKS.LAST_UPDATED</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>LINKS.LAST_CHECKED</code>.
     */
    public void setLastChecked(@NotNull LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>LINKS.LAST_CHECKED</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public LocalDateTime getLastChecked() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>LINKS.ZONE_OFFSET</code>.
     */
    public void setZoneOffset(@NotNull Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>LINKS.ZONE_OFFSET</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getZoneOffset() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row5<Long, String, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row5<Long, String, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Links.LINKS.LINK_ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Links.LINKS.URL;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field3() {
        return Links.LINKS.LAST_UPDATED;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field4() {
        return Links.LINKS.LAST_CHECKED;
    }

    @Override
    @NotNull
    public Field<Integer> field5() {
        return Links.LINKS.ZONE_OFFSET;
    }

    @Override
    @NotNull
    public Long component1() {
        return getLinkId();
    }

    @Override
    @NotNull
    public String component2() {
        return getUrl();
    }

    @Override
    @NotNull
    public LocalDateTime component3() {
        return getLastUpdated();
    }

    @Override
    @NotNull
    public LocalDateTime component4() {
        return getLastChecked();
    }

    @Override
    @NotNull
    public Integer component5() {
        return getZoneOffset();
    }

    @Override
    @NotNull
    public Long value1() {
        return getLinkId();
    }

    @Override
    @NotNull
    public String value2() {
        return getUrl();
    }

    @Override
    @NotNull
    public LocalDateTime value3() {
        return getLastUpdated();
    }

    @Override
    @NotNull
    public LocalDateTime value4() {
        return getLastChecked();
    }

    @Override
    @NotNull
    public Integer value5() {
        return getZoneOffset();
    }

    @Override
    @NotNull
    public LinksRecord value1(@NotNull Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value2(@NotNull String value) {
        setUrl(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value3(@NotNull LocalDateTime value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value4(@NotNull LocalDateTime value) {
        setLastChecked(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value5(@NotNull Integer value) {
        setZoneOffset(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord values(@NotNull Long value1, @NotNull String value2, @NotNull LocalDateTime value3, @NotNull LocalDateTime value4, @NotNull Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinksRecord
     */
    public LinksRecord() {
        super(Links.LINKS);
    }

    /**
     * Create a detached, initialised LinksRecord
     */
    @ConstructorProperties({ "linkId", "url", "lastUpdated", "lastChecked", "zoneOffset" })
    public LinksRecord(@NotNull Long linkId, @NotNull String url, @NotNull LocalDateTime lastUpdated, @NotNull LocalDateTime lastChecked, @NotNull Integer zoneOffset) {
        super(Links.LINKS);

        setLinkId(linkId);
        setUrl(url);
        setLastUpdated(lastUpdated);
        setLastChecked(lastChecked);
        setZoneOffset(zoneOffset);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinksRecord
     */
    public LinksRecord(edu.java.scrapper.domain.jooq.tables.pojos.Links value) {
        super(Links.LINKS);

        if (value != null) {
            setLinkId(value.getLinkId());
            setUrl(value.getUrl());
            setLastUpdated(value.getLastUpdated());
            setLastChecked(value.getLastChecked());
            setZoneOffset(value.getZoneOffset());
            resetChangedOnNotNull();
        }
    }
}
